framework:
  secret: '%env(APP_SECRET)%'
  handle_all_throwables: true
  http_method_override: false
  csrf_protection: false
  session:
    enabled: false
  serializer:
    enabled: true
  php_errors:
    log: true
